name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  ubuntu-deps: "dpkg-dev fakeroot libwebkit2gtk-4.1-0 libwebkit2gtk-4.1-dev libjavascriptcoregtk-4.1-0 libjavascriptcoregtk-4.1-dev gir1.2-javascriptcoregtk-4.1 gir1.2-webkit2-4.1 build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev desktop-file-utils libudev-dev rpm"

jobs:
  release:
    name: Build and Release
    strategy:
      fail-fast: false
      matrix:
        platform: 
          - ubuntu-latest
          - windows-2022
          - macos-13
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Set up Github Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install OS dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ env.ubuntu-deps }}
      - name: Install npm dependencies
        run: npm install
      - name: Build Application
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Arch Linux Package
        if: matrix.platform == 'ubuntu-latest'
        run: |
          docker run --rm -v "${{ github.workspace }}:/work" -w /work archlinux:latest bash -c "
          pacman -Syu --noconfirm curl git base-devel acpica dmidecode python &&
          useradd -m builduser &&
          echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers &&
          chown -R builduser:builduser /work &&

          su - builduser -c '
            set -e
            cd /work &&
            git clone https://aur.archlinux.org/yay.git &&
            cd yay &&
            makepkg -si --noconfirm &&

            yay -S --noconfirm coreboot-utils chromium-ectool cbmem || true &&

            curl https://sh.rustup.rs -sSf | bash -s -- -y &&
            source \$HOME/.cargo/env &&

            tauri_path=\$(find /work -type d -name \"src-tauri\" -print -quit) &&
            cd \"\$tauri_path\" || { echo \"src-tauri not found\"; exit 1; } &&

            mkdir -p target/release/bundle/arch/ &&
            cp target/release/bundle/deb/*.deb target/release/bundle/arch/ || true &&
            cp tauri.conf.json target/release/bundle/arch/ || true &&
            cp -r arch/* target/release/bundle/arch/ || true &&

            cd target/release/bundle/arch &&
            makepkg -sf --noconfirm
            cd ../../../../../
          ' "


      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Chrultrabook-Tools
          retention-days: 30
          path: |
            src-tauri/target/release/chrultrabook*.exe
            src-tauri/target/release/chrultrabook*.msi
            src-tauri/target/release/**/*.deb
            src-tauri/target/release/**/*.rpm
            src-tauri/target/release/**/*.tar.gz
            src-tauri/target/release/**/*.pkg.tar.zst
      - name: Upload Artifacts to GitHub Draft Release
        uses: softprops/action-gh-release@v2
        with:
          name: "draft_release"
          tag_name: v__VERSION__
          draft: true
          update_draft: true
          files: |
            src-tauri/target/release/chrultrabook*.exe
            src-tauri/target/release/chrultrabook*.msi
            src-tauri/target/release/**/*.deb
            src-tauri/target/release/**/*.rpm
            src-tauri/target/release/**/*.tar.gz
            src-tauri/target/release/**/*.pkg.tar.zst
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

